version: '3.8'


services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=message
    ports:
      - "5672:5672"
      - "15672:15672"

